version: '3'

services:
  youduchatgpt-dev:
    profiles: [ "dev" ]
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/www:ro
  youduchatgpt-pub:
    profiles: [ "pub" ]
    image: treerootboy/youduchatgpt
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}